name: preview
env:
  VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID_DEV }}
on:
  push:
    branches-ignore:
      - dev
      - main
jobs:
  deploy:
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.url }}
    runs-on: hatsuboshi
    steps:
      - uses: actions/checkout@v7
      - name: install vercel cli
        run: |
          npm install --global vercel@latest
      - name: build & deploy
        id: deploy
        run: |
          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --token=${{ secrets.VERCEL_TOKEN }}
          DEPLOY_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
          echo "url=$DEPLOY_URL" >> "$GITHUB_OUTPUT"
