name: main
env:
  VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID_PROD }}
on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment:
      name: production
      url: https://www.hatsuboshi.app
    runs-on: hatsuboshi
    steps:
      - uses: actions/checkout@v7
      - name: install vercel cli
        run: |
          npm install --global vercel@latest
      - name: build & deploy
        id: deploy
        run: |
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
